{% set name = "aeon-neuro" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aeon_neuro-{{ version }}.tar.gz
  sha256: 8510885223f466729339208c407c6bbf40f4a4c406301a45bbd8b129423e59c3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - setuptools >61
    - wheel
    - toml
    - python-build
    - pip
  run:
    - python >=3.8,<3.13
    - aeon <0.11.0
    - mne
    - pyprep

test:
  imports:
    - aeon_neuro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aeon-neuro.readthedocs.io/
  dev_url: https://github.com/aeon-toolkit/aeon-neuro/
  summary: A package for ECG and EEG time series analysis built on the aeon toolkit.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - griegner
    - MatthewMiddlehurst
